### ISSUE TITLE
Update to nestjs v8

### ISSUE THREAD

**Issue by alex-marczinek** [dollarsignteam/nestjs-jaeger-tracing#9]
I'm trying to update my service to nestjs v8. However this library depends on nestjs v7. Are there any plans to update to nestjs v8?

**Comment by anwam** [comment]
sorry for late reply, We have an unscheduled plan to update the lib to support NestJS 8 soon, but unfortunately, we're so busy and don't have much time to maintain this repo. 

anyway, if you want to do that, feel free to send PRs.

**Comment by ilesar** [comment]
resolves #10

**Comment by anwam** [comment]
resolve via #10
